[package]
name = "advent_of_code_day1"
version = "0.1.0"
authors = ["Josh Perry <joshperry@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
